### PR TITLE
highlight non-asf release in blog pages

### PR DESCRIPTION
**Pull request by chaokunyang**
image

### CODE REVIEW

**Review by tisonkun — CHANGES_REQUESTED** [review]
Thanks for taking care of this @chaokunyang! I suggest:

1. Update your title as `Apache Fury PPMC Member` to avoid argument on what 'Maintainer' means and 'Fury' vs. 'Apache Fury'.
2. The Note can be:

```mdx
::: info

This release was made before Fury joined the Apache Incubator and thus it's a non-ASF release.

:::
```

**Comment by chaokunyang** [comment]
> 1. Apache Fury PPMC Member

Thanks, updated:
image

**Review by tisonkun — APPROVED** [review]
LGTM.

I suggest you try to revise the `Fury - A blazing fast multi-language serialization framework powered by jit and zero-copy` blog later and keep the first and most prominent uses of Fury as "Apache Fury".

You may regard it as a revision of the featured blog and we can share it among the community and social media also.

**Comment by chaokunyang** [comment]
> LGTM.
> 
> I suggest you try to revise the `Fury - A blazing fast multi-language serialization framework powered by jit and zero-copy` blog later and keep the first and most prominent uses of Fury as "Apache Fury".
> 
> You may regard it as a revision of the featured blog and we can share it among the community and social media also.

Thanks for your suggestion, I updated in https://github.com/apache/incubator-fury-site/pull/115

**Comment by justinmclean** [comment]
Re "keep the first and most prominent uses of Fury as "Apache Fury" you need to take care that you don't call something "Apache Fury" when it was not an Apache release.

**Comment by tisonkun** [comment]
> Re "keep the first and most prominent uses of Fury as "Apache Fury" you need to take care that you don't call something "Apache Fury" when it was not an Apache release.

Yes. So you can regard it as we delete the old blog and write new blog for the current Apache Fury (incubating). Then it won't suffer from this concern.

**Pull request merged**
